name: Start Cron Loop
on:
  workflow_dispatch:
  push:
    paths:
      - 'restart.txt'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get install jq
      - name: Generate and Trigger Cron Jobs
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          now=$(date +%s)
          cronTimes=$(jq -c --arg now "$now" '[0,1,2,3,4] | map(($now | tonumber) + (. * 60) | strftime("%M %H * * *"))' <<< '[]')
          pending=$(echo "$cronTimes" | jq -r '.[] | {"cron": ., "status": "pending"}' | jq -s '.')
          echo "$pending" > pending.json
          cat <<EOF > .github/workflows/cron-jobs.yml
          name: Scheduled Cron Jobs
          on:
            schedule:
          $(echo "$cronTimes" | jq -r '.[] | "    - cron: \(. | tostring)"')
          jobs:
            execute-cron:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                - name: Install jq
                  run: sudo apt-get install jq
                - name: Execute Cron
                  run: |
                    timestamp=$(date -u -Iseconds)
                    executed=$(cat executed.json 2>/dev/null || echo '[]')
                    cron=$(date -u +"%M %H * * *")
                    echo "\$executed" | jq -c ". + [{\\"cron\\": \\"\$cron\\", \\"timestamp\\": \\"\$timestamp\\", \\"status\\": \\"done\\"}]" > executed.json
                    pending=$(cat pending.json 2>/dev/null || echo '[]')
                    pending=$(echo "\$pending" | jq -c "map(select(.cron != \\"\$cron\\"))")
                    echo "\$pending" > pending.json
                    if [ "$(echo "$cronTimes" | jq -r '.[-1]')" = "$cron" ] && [ ! -f stop.json ]; then
                      echo "Restarting..." > restart.txt
                    fi
                - name: Commit Changes
                  uses: stefanzweifel/git-auto-commit-action@v5
                  with:
                    commit_message: 'Update executed and pending jobs'
                    file_pattern: 'executed.json pending.json restart.txt'
          EOF
          echo "Generated cron times: $cronTimes"
      - name: Commit Changes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/cron-jobs.yml pending.json
          git commit -m "Update cron jobs and pending" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/lalaland83/cronjobs.git
          git push
      - name: Clean Restart File
        if: always()
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          if [ -f restart.txt ]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/lalaland83/cronjobs.git
            rm -f restart.txt
            git add restart.txt
            git commit -m "Clean restart file" || echo "No changes to commit"
            git push || echo "Push skipped"
          else
            echo "No restart.txt to clean"
          fi