name: Cron Job Runner

on:
  schedule:
    - cron: '0 * * * *' # Platzhalter, wird automatisch ersetzt
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run task and update schedules
        run: |
          npm install
          node run-task.js

      - name: Auto-commit updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update executed + regenerate schedule
          file_pattern: pending.json executed.json .github/workflows/cron-job.yml
