name: Execute Job

on:
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run job
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M")
          echo "🔁 Executing scheduled job at $NOW"
          node scripts/append_executed.js
      - name: Generate next schedule
        run: node scripts/generate_next_schedule.js
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Executed job + scheduled next"
          file_pattern: |
            executed.json
            pending.json
            .github/workflows/cron-jobs.yml
