name: Execute Job

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initial Setup
        run: echo "Initial placeholder – wird durch Script ersetzt."
