name: Start Cron Loop

on:
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Generate Script
        run: node .github/scripts/generate-pending.js

      - name: Commit new pending.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Start loop – generate new pending.json"
          file_pattern: pending.json
